// <auto-generated />
using System;
using BibliotecaUteco.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BibliotecaUteco.Migrations
{
    [DbContext(typeof(BibliotecaUtecoDbContext))]
    [Migration("20251011031448_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BibliotecaUteco.DataAccess.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NormalizedFullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedFullName")
                        .IsUnique();

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("BibliotecaUteco.DataAccess.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CoverUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Sinopsis")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Books");
                });

            modelBuilder.Entity("BibliotecaUteco.DataAccess.Models.BookAuthor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("AuthorId", "BookId")
                        .IsUnique();

                    b.ToTable("BookAuthors");
                });

            modelBuilder.Entity("BibliotecaUteco.DataAccess.Models.BookLoan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LoanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("LoanId", "BookId")
                        .IsUnique();

                    b.ToTable("BookLoans");
                });

            modelBuilder.Entity("BibliotecaUteco.DataAccess.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 11, 3, 14, 46, 488, DateTimeKind.Utc).AddTicks(8380),
                            Name = "Fantasía",
                            NormalizedName = "fantasia",
                            UpdatedAt = new DateTime(2025, 10, 11, 3, 14, 46, 488, DateTimeKind.Utc).AddTicks(8384)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 11, 3, 14, 46, 489, DateTimeKind.Utc).AddTicks(52),
                            Name = "Terror",
                            NormalizedName = "terror",
                            UpdatedAt = new DateTime(2025, 10, 11, 3, 14, 46, 489, DateTimeKind.Utc).AddTicks(53)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 10, 11, 3, 14, 46, 489, DateTimeKind.Utc).AddTicks(57),
                            Name = "Ciencia Ficción",
                            NormalizedName = "ciencia ficcion",
                            UpdatedAt = new DateTime(2025, 10, 11, 3, 14, 46, 489, DateTimeKind.Utc).AddTicks(57)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 10, 11, 3, 14, 46, 489, DateTimeKind.Utc).AddTicks(60),
                            Name = "Romance",
                            NormalizedName = "romance",
                            UpdatedAt = new DateTime(2025, 10, 11, 3, 14, 46, 489, DateTimeKind.Utc).AddTicks(61)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 10, 11, 3, 14, 46, 489, DateTimeKind.Utc).AddTicks(63),
                            Name = "Misterio",
                            NormalizedName = "misterio",
                            UpdatedAt = new DateTime(2025, 10, 11, 3, 14, 46, 489, DateTimeKind.Utc).AddTicks(64)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 10, 11, 3, 14, 46, 489, DateTimeKind.Utc).AddTicks(66),
                            Name = "Aventura",
                            NormalizedName = "aventura",
                            UpdatedAt = new DateTime(2025, 10, 11, 3, 14, 46, 489, DateTimeKind.Utc).AddTicks(67)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 10, 11, 3, 14, 46, 489, DateTimeKind.Utc).AddTicks(69),
                            Name = "Histórico",
                            NormalizedName = "historico",
                            UpdatedAt = new DateTime(2025, 10, 11, 3, 14, 46, 489, DateTimeKind.Utc).AddTicks(70)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 10, 11, 3, 14, 46, 489, DateTimeKind.Utc).AddTicks(73),
                            Name = "Biografía",
                            NormalizedName = "biografia",
                            UpdatedAt = new DateTime(2025, 10, 11, 3, 14, 46, 489, DateTimeKind.Utc).AddTicks(73)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 10, 11, 3, 14, 46, 489, DateTimeKind.Utc).AddTicks(77),
                            Name = "Poesía",
                            NormalizedName = "poesia",
                            UpdatedAt = new DateTime(2025, 10, 11, 3, 14, 46, 489, DateTimeKind.Utc).AddTicks(78)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 10, 11, 3, 14, 46, 489, DateTimeKind.Utc).AddTicks(80),
                            Name = "Drama",
                            NormalizedName = "drama",
                            UpdatedAt = new DateTime(2025, 10, 11, 3, 14, 46, 489, DateTimeKind.Utc).AddTicks(81)
                        });
                });

            modelBuilder.Entity("BibliotecaUteco.DataAccess.Models.GenreBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("GenreId", "BookId")
                        .IsUnique();

                    b.ToTable("GenreBooks");
                });

            modelBuilder.Entity("BibliotecaUteco.DataAccess.Models.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxLoanDays")
                        .HasColumnType("int");

                    b.Property<int>("ReaderId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReturnedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ReaderId");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("BibliotecaUteco.DataAccess.Models.Penalty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("DailyFineRate")
                        .HasColumnType("float");

                    b.Property<double>("GivenAmount")
                        .HasColumnType("float");

                    b.Property<bool>("IsDue")
                        .HasColumnType("bit");

                    b.Property<int>("LoanId")
                        .HasColumnType("int");

                    b.Property<int>("OverdueDays")
                        .HasColumnType("int");

                    b.Property<double>("ReturnedAmount")
                        .HasColumnType("float");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("float");

                    b.Property<int>("TransactionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LoanId")
                        .IsUnique();

                    b.HasIndex("TransactionId")
                        .IsUnique();

                    b.ToTable("Penalties");
                });

            modelBuilder.Entity("BibliotecaUteco.DataAccess.Models.Reader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdentityCardNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("StudentLicence")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdentityCardNumber")
                        .IsUnique();

                    b.HasIndex("StudentLicence")
                        .IsUnique()
                        .HasFilter("[StudentLicence] IS NOT NULL");

                    b.ToTable("Readers");
                });

            modelBuilder.Entity("BibliotecaUteco.DataAccess.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 11, 3, 14, 46, 398, DateTimeKind.Utc).AddTicks(1504),
                            Name = "Librarian",
                            UpdatedAt = new DateTime(2025, 10, 11, 3, 14, 46, 398, DateTimeKind.Utc).AddTicks(1508)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 11, 3, 14, 46, 398, DateTimeKind.Utc).AddTicks(2472),
                            Name = "Admin",
                            UpdatedAt = new DateTime(2025, 10, 11, 3, 14, 46, 398, DateTimeKind.Utc).AddTicks(2472)
                        });
                });

            modelBuilder.Entity("BibliotecaUteco.DataAccess.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("BibliotecaUteco.DataAccess.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdentityCardNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("IdentityCardNumber")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 11, 3, 14, 46, 415, DateTimeKind.Utc).AddTicks(9860),
                            FullName = "José Apolinar",
                            IdentityCardNumber = "00112345678",
                            Password = "973279fd3528bf897629f68765425a6b3e88e35b010c3c3c10a169283a817289",
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 10, 11, 3, 14, 46, 415, DateTimeKind.Utc).AddTicks(9865),
                            Username = "jose.apolinar"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 11, 3, 14, 46, 466, DateTimeKind.Utc).AddTicks(2544),
                            FullName = "Manuel López",
                            IdentityCardNumber = "00212345678",
                            Password = "2540fc2a209dd5946b09734722f16821b435db8e376655ab334379a4a0de1133",
                            RoleId = 2,
                            UpdatedAt = new DateTime(2025, 10, 11, 3, 14, 46, 466, DateTimeKind.Utc).AddTicks(2549),
                            Username = "manuel.lopez"
                        });
                });

            modelBuilder.Entity("BibliotecaUteco.DataAccess.Models.BookAuthor", b =>
                {
                    b.HasOne("BibliotecaUteco.DataAccess.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BibliotecaUteco.DataAccess.Models.Book", "Book")
                        .WithMany("Authors")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("BibliotecaUteco.DataAccess.Models.BookLoan", b =>
                {
                    b.HasOne("BibliotecaUteco.DataAccess.Models.Book", "Book")
                        .WithMany("Loans")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BibliotecaUteco.DataAccess.Models.Loan", "Loan")
                        .WithMany("Books")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("BibliotecaUteco.DataAccess.Models.GenreBook", b =>
                {
                    b.HasOne("BibliotecaUteco.DataAccess.Models.Book", "Book")
                        .WithMany("Genres")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BibliotecaUteco.DataAccess.Models.Genre", "Genre")
                        .WithMany("Books")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("BibliotecaUteco.DataAccess.Models.Loan", b =>
                {
                    b.HasOne("BibliotecaUteco.DataAccess.Models.Reader", "Reader")
                        .WithMany("Loans")
                        .HasForeignKey("ReaderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reader");
                });

            modelBuilder.Entity("BibliotecaUteco.DataAccess.Models.Penalty", b =>
                {
                    b.HasOne("BibliotecaUteco.DataAccess.Models.Loan", "Loan")
                        .WithOne("Penalty")
                        .HasForeignKey("BibliotecaUteco.DataAccess.Models.Penalty", "LoanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BibliotecaUteco.DataAccess.Models.Transaction", "Transaction")
                        .WithOne("Penalty")
                        .HasForeignKey("BibliotecaUteco.DataAccess.Models.Penalty", "TransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Loan");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("BibliotecaUteco.DataAccess.Models.Transaction", b =>
                {
                    b.HasOne("BibliotecaUteco.DataAccess.Models.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BibliotecaUteco.DataAccess.Models.User", b =>
                {
                    b.HasOne("BibliotecaUteco.DataAccess.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BibliotecaUteco.DataAccess.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("BibliotecaUteco.DataAccess.Models.Book", b =>
                {
                    b.Navigation("Authors");

                    b.Navigation("Genres");

                    b.Navigation("Loans");
                });

            modelBuilder.Entity("BibliotecaUteco.DataAccess.Models.Genre", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("BibliotecaUteco.DataAccess.Models.Loan", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("Penalty");
                });

            modelBuilder.Entity("BibliotecaUteco.DataAccess.Models.Reader", b =>
                {
                    b.Navigation("Loans");
                });

            modelBuilder.Entity("BibliotecaUteco.DataAccess.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("BibliotecaUteco.DataAccess.Models.Transaction", b =>
                {
                    b.Navigation("Penalty");
                });

            modelBuilder.Entity("BibliotecaUteco.DataAccess.Models.User", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
