// <auto-generated />
using System;
using BibliotecaUteco.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BibliotecaUteco.Migrations
{
    [DbContext(typeof(BibliotecaUtecoDbContext))]
    partial class BibliotecaUtecoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BibliotecaUteco.DataAccess.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreadoEn");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NombreCompleto");

                    b.Property<string>("NormalizedFullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NombreCompletoNormalizado");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ActualizadoEn");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedFullName")
                        .IsUnique();

                    b.ToTable("Autores");
                });

            modelBuilder.Entity("BibliotecaUteco.DataAccess.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CoverUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UrlPortada");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreadoEn");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Nombre");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NombreNormalizado");

                    b.Property<int>("Stock")
                        .HasColumnType("int")
                        .HasColumnName("Copias");

                    b.Property<string>("Synopsis")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Synopsis");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ActualizadoEn");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Libros");
                });

            modelBuilder.Entity("BibliotecaUteco.DataAccess.Models.BookAuthor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int")
                        .HasColumnName("IdAutor");

                    b.Property<int>("BookId")
                        .HasColumnType("int")
                        .HasColumnName("IdLibro");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreadoEn");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ActualizadoEn");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("AuthorId", "BookId")
                        .IsUnique();

                    b.ToTable("LibroAutor");
                });

            modelBuilder.Entity("BibliotecaUteco.DataAccess.Models.BookLoan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int")
                        .HasColumnName("IdLibro");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreadoEn");

                    b.Property<int>("LoanId")
                        .HasColumnType("int")
                        .HasColumnName("IdPrestamos");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ActualizadoEn");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("LoanId", "BookId")
                        .IsUnique();

                    b.ToTable("LibroPrestamo");
                });

            modelBuilder.Entity("BibliotecaUteco.DataAccess.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreadoEn");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("Nombre");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("NombreNormalizado");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ActualizadoEn");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Genero");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 12, 4, 35, 42, 189, DateTimeKind.Utc).AddTicks(5162),
                            Name = "Fantasía",
                            NormalizedName = "fantasia",
                            UpdatedAt = new DateTime(2025, 10, 12, 4, 35, 42, 189, DateTimeKind.Utc).AddTicks(5170)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 12, 4, 35, 42, 189, DateTimeKind.Utc).AddTicks(7002),
                            Name = "Terror",
                            NormalizedName = "terror",
                            UpdatedAt = new DateTime(2025, 10, 12, 4, 35, 42, 189, DateTimeKind.Utc).AddTicks(7004)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 10, 12, 4, 35, 42, 189, DateTimeKind.Utc).AddTicks(7008),
                            Name = "Ciencia Ficción",
                            NormalizedName = "cienciaficcion",
                            UpdatedAt = new DateTime(2025, 10, 12, 4, 35, 42, 189, DateTimeKind.Utc).AddTicks(7008)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 10, 12, 4, 35, 42, 189, DateTimeKind.Utc).AddTicks(7011),
                            Name = "Romance",
                            NormalizedName = "romance",
                            UpdatedAt = new DateTime(2025, 10, 12, 4, 35, 42, 189, DateTimeKind.Utc).AddTicks(7011)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 10, 12, 4, 35, 42, 189, DateTimeKind.Utc).AddTicks(7014),
                            Name = "Misterio",
                            NormalizedName = "misterio",
                            UpdatedAt = new DateTime(2025, 10, 12, 4, 35, 42, 189, DateTimeKind.Utc).AddTicks(7014)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 10, 12, 4, 35, 42, 189, DateTimeKind.Utc).AddTicks(7016),
                            Name = "Aventura",
                            NormalizedName = "aventura",
                            UpdatedAt = new DateTime(2025, 10, 12, 4, 35, 42, 189, DateTimeKind.Utc).AddTicks(7017)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 10, 12, 4, 35, 42, 189, DateTimeKind.Utc).AddTicks(7019),
                            Name = "Histórico",
                            NormalizedName = "historico",
                            UpdatedAt = new DateTime(2025, 10, 12, 4, 35, 42, 189, DateTimeKind.Utc).AddTicks(7020)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 10, 12, 4, 35, 42, 189, DateTimeKind.Utc).AddTicks(7022),
                            Name = "Biografía",
                            NormalizedName = "biografia",
                            UpdatedAt = new DateTime(2025, 10, 12, 4, 35, 42, 189, DateTimeKind.Utc).AddTicks(7023)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 10, 12, 4, 35, 42, 189, DateTimeKind.Utc).AddTicks(7025),
                            Name = "Poesía",
                            NormalizedName = "poesia",
                            UpdatedAt = new DateTime(2025, 10, 12, 4, 35, 42, 189, DateTimeKind.Utc).AddTicks(7025)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 10, 12, 4, 35, 42, 189, DateTimeKind.Utc).AddTicks(7028),
                            Name = "Drama",
                            NormalizedName = "drama",
                            UpdatedAt = new DateTime(2025, 10, 12, 4, 35, 42, 189, DateTimeKind.Utc).AddTicks(7028)
                        });
                });

            modelBuilder.Entity("BibliotecaUteco.DataAccess.Models.GenreBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int")
                        .HasColumnName("IdLibro");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreadoEn");

                    b.Property<int>("GenreId")
                        .HasColumnType("int")
                        .HasColumnName("IdGenero");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ActualizadoEn");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("GenreId", "BookId")
                        .IsUnique();

                    b.ToTable("GeneroLibro");
                });

            modelBuilder.Entity("BibliotecaUteco.DataAccess.Models.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreadoEn");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DiaDeEntrega");

                    b.Property<int>("MaxLoanDays")
                        .HasColumnType("int")
                        .HasColumnName("MaxDiasDePrestamo");

                    b.Property<int>("ReaderId")
                        .HasColumnType("int")
                        .HasColumnName("IdLector");

                    b.Property<DateTime?>("ReturnedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DiaDevuelto");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ActualizadoEn");

                    b.HasKey("Id");

                    b.HasIndex("ReaderId");

                    b.ToTable("Prestamos");
                });

            modelBuilder.Entity("BibliotecaUteco.DataAccess.Models.Penalty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreadoEn");

                    b.Property<double>("DailyFineRate")
                        .HasColumnType("float")
                        .HasColumnName("TazaDeMultaPorDia");

                    b.Property<double>("GivenAmount")
                        .HasColumnType("float")
                        .HasColumnName("MontoDado");

                    b.Property<bool>("IsDue")
                        .HasColumnType("bit")
                        .HasColumnName("EsDebida");

                    b.Property<int>("LoanId")
                        .HasColumnType("int")
                        .HasColumnName("IdPrestamo");

                    b.Property<int>("OverdueDays")
                        .HasColumnType("int")
                        .HasColumnName("DiasExcedidos");

                    b.Property<double>("ReturnedAmount")
                        .HasColumnType("float")
                        .HasColumnName("MontoDevuelto");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("float")
                        .HasColumnName("TotalAPagar");

                    b.Property<int>("TransactionId")
                        .HasColumnType("int")
                        .HasColumnName("IdTransaccion");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ActualizadoEn");

                    b.HasKey("Id");

                    b.HasIndex("LoanId")
                        .IsUnique();

                    b.HasIndex("TransactionId")
                        .IsUnique();

                    b.ToTable("Penalizaciones");
                });

            modelBuilder.Entity("BibliotecaUteco.DataAccess.Models.Reader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Direccion");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreadoEn");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NombreCompleto");

                    b.Property<string>("IdentityCardNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("Cedula");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("NumeroDeTelefono");

                    b.Property<string>("StudentLicence")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)")
                        .HasColumnName("Matricula");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ActualizadoEn");

                    b.HasKey("Id");

                    b.HasIndex("IdentityCardNumber")
                        .IsUnique();

                    b.HasIndex("StudentLicence")
                        .IsUnique()
                        .HasFilter("[Matricula] IS NOT NULL");

                    b.ToTable("Lectores");
                });

            modelBuilder.Entity("BibliotecaUteco.DataAccess.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreadoEn");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("Nombre");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ActualizadoEn");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 12, 4, 35, 42, 64, DateTimeKind.Utc).AddTicks(7244),
                            Name = "Librarian",
                            UpdatedAt = new DateTime(2025, 10, 12, 4, 35, 42, 64, DateTimeKind.Utc).AddTicks(7251)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 12, 4, 35, 42, 64, DateTimeKind.Utc).AddTicks(9205),
                            Name = "Admin",
                            UpdatedAt = new DateTime(2025, 10, 12, 4, 35, 42, 64, DateTimeKind.Utc).AddTicks(9217)
                        });
                });

            modelBuilder.Entity("BibliotecaUteco.DataAccess.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("float")
                        .HasColumnName("Monto");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreadoEn");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ActualizadoEn");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("IdUsuario");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TransaccionesCaja");
                });

            modelBuilder.Entity("BibliotecaUteco.DataAccess.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreadoEn");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NombreCompleto");

                    b.Property<string>("IdentityCardNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("Cedula");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Clave");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UrlFotoDePerfil");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("IdRole");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ActualizadoEn");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("NombreDeUsuario");

                    b.HasKey("Id");

                    b.HasIndex("IdentityCardNumber")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 12, 4, 35, 42, 79, DateTimeKind.Utc).AddTicks(8624),
                            FullName = "José Apolinar",
                            IdentityCardNumber = "00112345678",
                            Password = "973279fd3528bf897629f68765425a6b3e88e35b010c3c3c10a169283a817289",
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 10, 12, 4, 35, 42, 79, DateTimeKind.Utc).AddTicks(8630),
                            Username = "jose.apolinar"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 12, 4, 35, 42, 144, DateTimeKind.Utc).AddTicks(8516),
                            FullName = "Manuel López",
                            IdentityCardNumber = "00212345678",
                            Password = "2540fc2a209dd5946b09734722f16821b435db8e376655ab334379a4a0de1133",
                            RoleId = 2,
                            UpdatedAt = new DateTime(2025, 10, 12, 4, 35, 42, 144, DateTimeKind.Utc).AddTicks(8521),
                            Username = "manuel.lopez"
                        });
                });

            modelBuilder.Entity("BibliotecaUteco.DataAccess.Models.BookAuthor", b =>
                {
                    b.HasOne("BibliotecaUteco.DataAccess.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BibliotecaUteco.DataAccess.Models.Book", "Book")
                        .WithMany("Authors")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("BibliotecaUteco.DataAccess.Models.BookLoan", b =>
                {
                    b.HasOne("BibliotecaUteco.DataAccess.Models.Book", "Book")
                        .WithMany("Loans")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BibliotecaUteco.DataAccess.Models.Loan", "Loan")
                        .WithMany("Books")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("BibliotecaUteco.DataAccess.Models.GenreBook", b =>
                {
                    b.HasOne("BibliotecaUteco.DataAccess.Models.Book", "Book")
                        .WithMany("Genres")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BibliotecaUteco.DataAccess.Models.Genre", "Genre")
                        .WithMany("Books")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("BibliotecaUteco.DataAccess.Models.Loan", b =>
                {
                    b.HasOne("BibliotecaUteco.DataAccess.Models.Reader", "Reader")
                        .WithMany("Loans")
                        .HasForeignKey("ReaderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reader");
                });

            modelBuilder.Entity("BibliotecaUteco.DataAccess.Models.Penalty", b =>
                {
                    b.HasOne("BibliotecaUteco.DataAccess.Models.Loan", "Loan")
                        .WithOne("Penalty")
                        .HasForeignKey("BibliotecaUteco.DataAccess.Models.Penalty", "LoanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BibliotecaUteco.DataAccess.Models.Transaction", "Transaction")
                        .WithOne("Penalty")
                        .HasForeignKey("BibliotecaUteco.DataAccess.Models.Penalty", "TransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Loan");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("BibliotecaUteco.DataAccess.Models.Transaction", b =>
                {
                    b.HasOne("BibliotecaUteco.DataAccess.Models.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BibliotecaUteco.DataAccess.Models.User", b =>
                {
                    b.HasOne("BibliotecaUteco.DataAccess.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BibliotecaUteco.DataAccess.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("BibliotecaUteco.DataAccess.Models.Book", b =>
                {
                    b.Navigation("Authors");

                    b.Navigation("Genres");

                    b.Navigation("Loans");
                });

            modelBuilder.Entity("BibliotecaUteco.DataAccess.Models.Genre", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("BibliotecaUteco.DataAccess.Models.Loan", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("Penalty");
                });

            modelBuilder.Entity("BibliotecaUteco.DataAccess.Models.Reader", b =>
                {
                    b.Navigation("Loans");
                });

            modelBuilder.Entity("BibliotecaUteco.DataAccess.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("BibliotecaUteco.DataAccess.Models.Transaction", b =>
                {
                    b.Navigation("Penalty");
                });

            modelBuilder.Entity("BibliotecaUteco.DataAccess.Models.User", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
